Feat: Add ElasticSearch query resolver
dappforce/subsocial-squid pull request #8
Opened 2023-02-20 07:07 UTC by mckrava

2023-02-20 07:10 UTC, mckrava commented
Subsocial SDK should be updated to fix hardcoded types in the squid.

2023-02-24 09:34 UTC, olehmell requested changes

2023-02-24 09:34 UTC, olehmell commented on package.json
>      "@subsocial/types": "^0.6.11",
Update utils and remove @subsocial/types

2023-02-24 09:34 UTC, olehmell commented on src/elasticsearch/esSearch.ts
> +
Looks like you have same code for instance creating, so maybe can you extract it to parent class and use for both cildren?

2023-02-24 09:34 UTC, olehmell commented on src/elasticsearch/mappings/profiles.json
> +{
remove it

2023-02-24 09:34 UTC, olehmell commented on src/elasticsearch/searchUtils.ts
> +import {
Make sense extract it to SDK, do we have a task?

2023-05-02 13:28 UTC, olehmell approved these changes

2023-05-02 13:29 UTC, merged